# Site settings
title: Olivier Harris
email: o.harris@kabucreative.com
description: > # this means to ignore newlines until "baseurl:"
  Web developer, project manager & co-founder of Kabu Creative.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ojh.github.io" # the base hostname & protocol for your site
twitter_username: OlivierHarris
github_username: ojh

# Build settings
markdown: kramdown
kramdown:
  input: GFM

timezone: Europe/London
collections:
  projects:
    output: true
    permalink: /:path/
